### ISSUE TITLE
Support for @trpc/server/adapters/fetch

### ISSUE THREAD

**Issue by zelid** [prosepilot/trpc-openapi#363] opened 2023-07-30 11:07 UTC
Hello,

How to use [trpc-openapi](https://github.com/prosepilot/trpc-openapi) with `fetchRequestHandler` (@trpc/server/adapters/fetch)?

`trpc-openapi` has `serverless` integration but it's actually `aws` only and not actually serverless. There are many serverless platforms which are not aws: cloudflare pages/workers, netlify, vercel, deno, fastly. They all can be handled in one-go with HatTip (example for Cloudflare workers: https://github.com/hattipjs/hattip/tree/main/examples/basic)

HatTip is based on Fetch API which is supported on serverless platforms.

This is how I define a working serverless trpc handler for HatTip but *without* trpc-openapi:
```
const trpcHandler = async (ctx: RequestContext) => {
  if (ctx.url.pathname.startsWith("/_trpc")) {
    const trpcHandler = await fetchRequestHandler({
      endpoint: "/_trpc",
      req: ctx.request,
      router: trpcAppRouter,
      // @ts-ignore
      createContext: createContext,
    });

    if (trpcHandler) {
      return new Response(trpcHandler.body, {
        status: trpcHandler.status,
        headers: {
          "Content-Type":
            trpcHandler.headers.get("Content-Type") || "application/json",
        },
      });
    }
  }
};
```

Few questions appear:
1) is it possible to port trpc-openapi to be used with  `fetch` API instead of node's `http` module? The reason is to make trpc-openapi fully serverless.
2) does it make sense to make trpc-openapi be ran on servelsess environments taking into consideration that swagger-ui requires Express (if I'm not mistaken)?

**Comment by zelid** [comment] 2023-07-30 11:47
WIP I'm trying to do by myself with ChatGPT help:

This is a high-level transformation from the original Express-like (Node HTTP) to Hattip and Fetch-like handling. Some parts of your original logic might need more specific changes, especially where you deal with sending responses or handling errors. I suggest you to look into the specific needs of your application logic and adjust the above code accordingly.

```
import { AnyProcedure, TRPCError } from '@trpc/server';
import { FetchHandlerOptions, fetchRequestHandler, FetchCreateContextFn } from '@trpc/server/adapters/fetch';
import cloneDeep from 'lodash.clonedeep';
import { ZodError, z } from 'zod';

import { generateOpenApiDocument } from '../../generator';
import {
  OpenApiErrorResponse,
  OpenApiMethod,
  OpenApiRouter,
  OpenApiSuccessResponse,
} from '../../types';
import { acceptsRequestBody } from '../../utils/method';
import { normalizePath } from '../../utils/path';
import { getInputOutputParsers } from '../../utils/procedure';
import {
  instanceofZodTypeCoercible,
  instanceofZodTypeLikeVoid,
  instanceofZodTypeObject,
  unwrapZodType,
  zodSupportsCoerce,
} from '../../utils/zod';
import { TRPC_ERROR_CODE_HTTP_STATUS, getErrorFromUnknown } from './errors';
import { getBody, getQuery } from './input';
import { createProcedureCache } from './procedures';

export type CreateOpenApiFetchHandlerOptions<
  TRouter extends OpenApiRouter,
> = Pick<
  FetchHandlerOptions<TRouter>,
  'router' | 'createContext' | 'responseMeta' | 'onError' | 'maxBodySize'
>;

export const createOpenApiFetchHandler = <
  TRouter extends OpenApiRouter,
>(
  opts: CreateOpenApiFetchHandlerOptions<TRouter>,
) => {
  const router = cloneDeep(opts.router);

  // Validate router
  if (process.env.NODE_ENV !== 'production') {
    generateOpenApiDocument(router, { title: '', version: '', baseUrl: '' });
  }

  const { createContext, responseMeta, onError, maxBodySize } = opts;
  const getProcedure = createProcedureCache(router);

  return fetchRequestHandler({
    createContext: createContext as FetchCreateContextFn,
    router: router,
    async onRequest: async (ctx: RequestContext) => {
      const method = ctx.method as OpenApiMethod & 'HEAD';
      const url = ctx.url;
      const path = normalizePath(url.pathname);
      const { procedure, pathInput } = getProcedure(method, path) ?? {};

      // continue with your previous logic, replacing req and res with ctx
      // Use ctx.next() where you would have used res.json(), res.send() or similar in Express
      // Use ctx.handleError(error) where you would have used next(error) in Express
      // Note: You might need to modify ctx.next() or ctx.handleError() calls based on your specific needs

      // ...

    },
  });
};

```

**Comment by nwparker** [comment] 2023-08-08 04:40
I think this is a duplicate of #188

**Closed** 2023-08-08 07:28 UTC
